# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/refs/heads/main/schema/compose-spec.json
services:
  db:
    image: postgres:16-alpine
    container_name: myapp-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5732:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    networks:
      - myapp-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: myapp-redis
    command: ["redis-server", "--maxmemory", "50mb", "--maxmemory-policy", "allkeys-lru"]
    ports:
      - "6379:6379"
    networks:
      - myapp-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: myapp-rabbitmq
    ports:
      - "5672:5672"
    networks:
      - myapp-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    container_name: myapp-caddy
    ports:
      - "8090:80"
      - "15672:15672"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - myapp-net
    depends_on:
      - rabbitmq

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: myapp-otel-collector
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:13133/"]
      interval: 5s
      retries: 5
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - myapp-net

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: myapp-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    networks:
      - myapp-net

  prometheus:
    image: prom/prometheus:latest
    container_name: myapp-prometheus
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - myapp-net

networks:
  myapp-net:
    driver: overlay
    external: true
    attachable: true

volumes:
  pg_data:
